travis:
  secure:
    BINSTAR_TOKEN: TDKmrGPj/PjhS9ddKm3/M1RXplhXroO9cIZDM+OBl+IOa8uewdM3gQBxu292H5UO+COsZgLLu7FO3Nsnrk9RH8pu69gjE/yc6cOifxF1nrZ76N4Sf9W/v6qS6xO+2V5/gA2XVMVjgZY11yrJWz4Z0bfhncGRIRNyBSCDP0kYjJWmPL6gp4J2rBahsMGpxDoviKXAjMi/WleESjGOWcJD9Jw7+WbNPBj94t8ccCareqE6gbxqa8cF5NNxxPvwsmr2BHwBEO9A12KIJN7AEbKeySws+KEwIye8LjdaJ/bAw6lt67UMzwhasLFM+qV6NlLNYdzYKTHVAPaEY2wSHzc9+cPo/oU3AXCRfu+3usMblppnCOMZdRkW/9AXBhmbgsX5lSkLTrgP/NVcXnpHqfFBMx5FyvtXRW8+SOTuqgGrmu9d54nLvc++SBoorKtt6Xqiyp2HyKiRCf0HRj/nai25lzaGUeTuCfz6zdWxDB7AtqCu5MTR7Zm2Q56Udzu6/c/19dq252bU2dArkif+wqJix+9qLk9qrziLxBKtClE0cfwl9wXzkypjroQbU7dbPYYN/QC5hVN2sy+ZrGfGC9HPFtLbeN6LZ8ETXSANV901sp8iHU6sLUiIq3k7BK4M8moa5lL4OBMrgx+c7LDMPA9DHCXRqadEu+bajai12zxKNRo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
