travis:
  secure:
    BINSTAR_TOKEN: tV41Uzl5qvflU2WxOfmIly1mO7wvHO8DlDRNxNbSbuVsAgv3ae6jcYrNi/rB4w6uXiH6FtqEdLbchuP1zIM9U3Sv1u+H6yBtUye7meH3H+5BpIY0Mw2ER4FK7fAmaQR5lAnigpJFC6fDzUId5OxrP9DN3ecZdJTMz8iLjAzVojtxyU7T4TDtoDKdelvyAQAAyHVUVUFy/qVyxFqxU4IQyP6UCSvwnxE6otbL02E+kFvk918FxtBmGUdk8p1k8ZMMB416uPHSDGUml5sN3qdGQQVOE4brgb+ZarIvbtlq+gYoAnfS3Lg2cDVtDmsJ1e4I7B3nObfozh3svppWeaw6cbwWKnaZwM7iq85zUQAGwnFSDjKQq41Vd1QvEuJ5YFhkVUYvneCjy7QgcO2MNa0/rhu9j2acMt4jmDbni/joALQlJNtKpLofiYFTLZneeN9MDkatsS7WBaIPuNxxxTymjKAwx85t2NaFGkW2WmVCHE2ekl943eTxdq099HN9rxKttK98KD7jOTn9tHcwRbMtjALoZwwpLP8DJku6mFu9Rn/vrR90OawDaRnth8cqNnd99LX4qVU1/jz7O6ufJlzyrV19744Sbo7KvgMnjdzvSIluKwQR0VVzXm4S09aK3SKAIj0u46uxN8ew5/7StzFnxoAUw7YSX8CJp8uOUwBLzyE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
